#!/usr/bin/env python

import sys

######################################
#
#import roslib
#
#pkg = 'rqt_dyros'
#roslib.load_manifest(pkg)
#
#from rqt_gui.main import Main
#
#main = Main()
#sys.exit(main.main(sys.argv, standalone=pkg))
#
######################################
from rqt_dyros.husky_panda import HuskyPanda
from rqt_gui.main import Main

plugin = 'rqt_dyros'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
